from .application_analysis import (
  AI_SUGGESTIONS_PROMPT,
  SKILL_REQUIRED_SCORE_PROMPT,
  SKILL_RESUME_SCORE_PROMPT,
)
from .company_insights import COMPANY_INSIGHTS_PROMPT, LINK_SELECTION_PROMPT
from .listing_extraction import LISTING_EXTRACTION_PROMPT
from .resume_optimization import (
  LISTING_CONTEXT,
  OPTIMIZE_DETAILED_ITEM_PROMPT,
  OPTIMIZE_PARAGRAPH_SECTION_PROMPT,
  OPTIMIZE_SIMPLE_SECTION_PROMPT,
)

__all__ = [
  'COMPANY_INSIGHTS_PROMPT',
  'AI_SUGGESTIONS_PROMPT',
  'SKILL_REQUIRED_SCORE_PROMPT',
  'SKILL_RESUME_SCORE_PROMPT',
  'LINK_SELECTION_PROMPT',
  'LISTING_EXTRACTION_PROMPT',
  'LISTING_CONTEXT',
  'OPTIMIZE_DETAILED_ITEM_PROMPT',
  'OPTIMIZE_PARAGRAPH_SECTION_PROMPT',
  'OPTIMIZE_SIMPLE_SECTION_PROMPT',
]
