import argparse
import asyncio
import sys
from pathlib import Path

# The script is intentionally outside the backend package; add backend/ for local CLI usage.
# ruff: noqa: E402
BACKEND_DIR = Path(__file__).resolve().parents[2]
SCRIPT_DIR = Path(__file__).resolve().parent
for import_path in [BACKEND_DIR, SCRIPT_DIR]:
  if str(import_path) not in sys.path:
    sys.path.insert(0, str(import_path))

from analysis import populate_actual_analyses
from builder import PAPER_FIXTURE_ANCHOR_DATE, build_fixture
from llm import generate_listings

from app.schemas.profile import Profile
from app.schemas.resume import Resume
from app.services.paper_mode.schemas import PaperFixture

DEFAULT_OUTPUT = BACKEND_DIR / 'app' / 'assets' / 'paper_data.json'
DEFAULT_PROFILE_SEED = SCRIPT_DIR / 'profile.json'
DEFAULT_RESUME_SEED = SCRIPT_DIR / 'resume.json'
DEFAULT_COUNT = 50


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(
    description='Generate the local-only Paper Mode fixture JSON.',
  )
  parser.add_argument('--count', type=int, default=DEFAULT_COUNT)
  parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
  parser.add_argument('--profile-seed', type=Path, default=DEFAULT_PROFILE_SEED)
  parser.add_argument('--resume-seed', type=Path, default=DEFAULT_RESUME_SEED)
  parser.add_argument('--validate-only', action='store_true')
  parser.add_argument('--force', action='store_true')
  args = parser.parse_args()

  if args.count <= 0:
    parser.error('--count must be greater than 0')

  if not args.validate_only and args.output.exists() and not args.force:
    parser.error(f'{args.output} already exists; pass --force to overwrite')

  if not args.validate_only:
    if not args.profile_seed.exists():
      parser.error(f'{args.profile_seed} does not exist')
    if not args.resume_seed.exists():
      parser.error(f'{args.resume_seed} does not exist')

  return args


async def main() -> None:
  args = parse_args()

  if args.validate_only:
    fixture = PaperFixture.model_validate_json(args.output.read_text(encoding='utf-8'))
    print(
      f'Parsed {args.output} '
      f'({len(fixture.listings)} listings, {len(fixture.applications)} applications).'
    )
    return

  seed = load_generation_seed(
    profile_path=args.profile_seed,
    resume_path=args.resume_seed,
  )
  listing_responses = await generate_listings(
    count=args.count,
  )
  fixture = build_fixture(seed=seed, listing_responses=listing_responses)
  fixture = await populate_actual_analyses(fixture)

  args.output.parent.mkdir(parents=True, exist_ok=True)
  args.output.write_text(fixture.model_dump_json(by_alias=True, indent=2) + '\n')
  print(
    f'Wrote {len(fixture.listings)} listings and '
    f'{len(fixture.applications)} applications to {args.output}.'
  )


# Profile and resume are not generated by fixture generation
def load_generation_seed(*, profile_path: Path, resume_path: Path) -> PaperFixture:
  return PaperFixture(
    anchor_date=PAPER_FIXTURE_ANCHOR_DATE,
    profile=Profile.model_validate_json(profile_path.read_text(encoding='utf-8')),
    resumes=[Resume.model_validate_json(resume_path.read_text(encoding='utf-8'))],
    listings=[],
    applications=[],
  )


if __name__ == '__main__':
  asyncio.run(main())
